version: "3.9"

services:

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ../docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/opt/pavepo_test_task/
    entrypoint: docker/entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db